### ISSUE TITLE
bazel-remote v1.3 failed with the following stacktrace

### ISSUE THREAD

**Issue by mehmetg** [buchgr/bazel-remote#394]
The server generated pages and pages of logs like this and died. It returned to normal after restart.

Any idea what this could be caused by ? 

```goroutine 14727760 [runnable]:
syscall.Syscall(0x0, 0x59b, 0xc02307a880, 0xd06, 0xd06, 0xd06, 0x0)
	src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x59b, 0xc02307a880, 0xd06, 0xd06, 0x0, 0x0, 0x203015)
	GOROOT/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
syscall.Read(...)
	GOROOT/src/syscall/syscall_unix.go:187
internal/poll.(*FD).Read.func1(0x7ffff800000, 0x2, 0xc050374ba8)
	GOROOT/src/internal/poll/fd_unix.go:155 +0x4c
internal/poll.ignoringEINTR(0xc0529bb8e0, 0x72, 0xc054e10301, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:567 +0x27
internal/poll.(*FD).Read(0xc050374ba0, 0xc02307a880, 0xd06, 0xd06, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:155 +0x13e
os.(*File).read(...)
	GOROOT/src/os/file_posix.go:31
os.(*File).Read(0xc004d18810, 0xc02307a880, 0xd06, 0xd06, 0xd06, 0xe3ffc0, 0xc004d18810)
	GOROOT/src/os/file.go:116 +0x71
github.com/buchgr/bazel-remote/server.(*grpcServer).Read(0xc00920c1b0, 0xc042271400, 0xe50140, 0xc051dc42b0, 0x0, 0x0)
	server/grpc_bytestream.go:96 +0x82c
google.golang.org/genproto/googleapis/bytestream._ByteStream_Read_Handler(0xd10760, 0xc00920c1b0, 0xe4db60, 0xc04223d0c0, 0x22, 0xc0422713b0)
	bazel-out/k8-fastbuild-ST-dc1f9eeaaa12/bin/external/go_googleapis/google/bytestream/bytestream_go_proto_/google.golang.org/genproto/googleapis/bytestream/bytestream.pb.go:697 +0x10b
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0xd10760, 0xc00920c1b0, 0xe4dda0, 0xc0427a9380, 0xc04223d0a0, 0xd83e88, 0xe495c0, 0xc04225ae10)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:121 +0xef
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003576c0, 0xe517c0, 0xc0330b5c80, 0xc043477d00, 0xc00920c3f0, 0x12fe2a0, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1434 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0003576c0, 0xe517c0, 0xc0330b5c80, 0xc043477d00, 0x0)
	external/org_golang_google_grpc/server.go:1507 +0xc9c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004e45b0, 0xc0003576c0, 0xe517c0, 0xc0330b5c80, 0xc043477d00)
	external/org_golang_google_grpc/server.go:843 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:841 +0x1fd

goroutine 14737848 [semacquire]:
sync.runtime_SemacquireMutex(0xc0001aaf54, 0x6033fe00, 0x1)
	GOROOT/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0001aaf50)
	GOROOT/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
	GOROOT/src/sync/mutex.go:81
log.(*Logger).Output(0xc0001aaf50, 0x2, 0xc03883fb20, 0x6a, 0x0, 0x0)
	GOROOT/src/log/log.go:162 +0x40e
log.(*Logger).Printf(0xc0001aaf50, 0xd5a30d, 0x21, 0xc0581b86d0, 0x1, 0x1)
	GOROOT/src/log/log.go:188 +0x7e
github.com/buchgr/bazel-remote/server.(*grpcServer).Read(0xc00920c1b0, 0xc066094dc0, 0xe50140, 0xc0581b8680, 0x0, 0x0)
	server/grpc_bytestream.go:118 +0xb22
google.golang.org/genproto/googleapis/bytestream._ByteStream_Read_Handler(0xd10760, 0xc00920c1b0, 0xe4db60, 0xc06184b4c0, 0x22, 0xc066094d70)
	bazel-out/k8-fastbuild-ST-dc1f9eeaaa12/bin/external/go_googleapis/google/bytestream/bytestream_go_proto_/google.golang.org/genproto/googleapis/bytestream/bytestream.pb.go:697 +0x10b
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0xd10760, 0xc00920c1b0, 0xe4dda0, 0xc05a8ce9c0, 0xc06184b4a0, 0xd83e88, 0xe495c0, 0xc061845e00)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:121 +0xef
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003576c0, 0xe517c0, 0xc0330b5c80, 0xc02a59d600, 0xc00920c3f0, 0x12fe2a0, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1434 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0003576c0, 0xe517c0, 0xc0330b5c80, 0xc02a59d600, 0x0)
	external/org_golang_google_grpc/server.go:1507 +0xc9c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004e45b0, 0xc0003576c0, 0xe517c0, 0xc0330b5c80, 0xc02a59d600)
	external/org_golang_google_grpc/server.go:843 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:841 +0x1fd```

**Comment by mostynb** [comment]
Do you have more of the logs? I think the part you pasted here shows two goroutines that were functioning normally when the server died (one is waiting for a lock inside the logger, the other is reading from a file).

IIRC when a go program panics it normally shows the stack trace of the goroutine that panicked first.

**Comment by mehmetg** [comment]
Unfortunately the logs got rotated rather quickly. I'll need to adjust log rotation settings and hope that I catch it on time this time around.

**Comment by mehmetg** [comment]
I checked again after a failure and it looks like the panic was not captured in 16MB+ of logs. 
Could this be some sort of deadlock where the app spins up go routines that wait on each other?

**Comment by mostynb** [comment]
Has this happened more than once for you?

Deadlocks happen when all processes are stuck, but one of the two goroutines was reading from a file, which I don't think can be (permanently) stuck.

**Comment by mehmetg** [comment]
I was able to dig up the beginning of the stack trace. 
thread exhaustion is the root, but to be honest could not dig into it much.
And yes this happens often under load more so than the older version we have been running twice a day. 
```Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:622 +0xac
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:636 +0x3e
Feb 22, 2021 @ 21:50:05.069 runtime.sysmon()
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:1172 +0xc8
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x45
Feb 22, 2021 @ 21:50:05.069 internal/poll.(*pollDesc).waitRead(...)
Feb 22, 2021 @ 21:50:05.069 net.(*netFD).accept(0xc0001b2400, 0x122fce09ed05284, 0x0, 0x0)
Feb 22, 2021 @ 21:50:05.069 net.(*TCPListener).accept(0xc010c4bde0, 0x60349760, 0xc009791698, 0x48e5a6)
Feb 22, 2021 @ 21:50:05.069     main.go:545 +0xe05
Feb 22, 2021 @ 21:50:05.069     external/com_github_urfave_cli_v2/app.go:315 +0x70d
Feb 22, 2021 @ 21:50:05.069     main.go:548 +0x1b06
Feb 22, 2021 @ 21:50:05.069 internal/poll.runtime_pollWait(0x7f274d0a26f0, 0x72, 0x0)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x45
Feb 22, 2021 @ 21:50:05.069 fatal error: thread exhaustion
Feb 22, 2021 @ 21:50:05.069 runtime.throw(0xd4cc90, 0x11)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/panic.go:1116 +0x72
Feb 22, 2021 @ 21:50:05.069 runtime.startm(0xc000073000, 0x130fd00)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:2001 +0x52
Feb 22, 2021 @ 21:50:05.069 runtime.retake(0x836a68a67fc58, 0xc000048800)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:4734 +0x1b1
Feb 22, 2021 @ 21:50:05.069 runtime.mstart1()
Feb 22, 2021 @ 21:50:05.069 runtime.mstart()
Feb 22, 2021 @ 21:50:05.069 goroutine 1 [IO wait]:
Feb 22, 2021 @ 21:50:05.069 internal/poll.runtime_pollWait(0x7f274d0a27d8, 0x72, 0x0)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/internal/poll/fd_poll_runtime.go:92
Feb 22, 2021 @ 21:50:05.069 internal/poll.(*FD).Accept(0xc0001b2400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/internal/poll/fd_unix.go:394 +0x1fc
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/net/fd_unix.go:172 +0x45
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/net/tcpsock.go:261 +0x65
Feb 22, 2021 @ 21:50:05.069 net/http.(*Server).ListenAndServe(0xc00039c2a0, 0x2, 0x2)
Feb 22, 2021 @ 21:50:05.069 main.main.func1(0xc0001a1400, 0xc000508000, 0x40)
Feb 22, 2021 @ 21:50:05.069 github.com/urfave/cli/v2.(*App).Run(...)
Feb 22, 2021 @ 21:50:05.069 main.main()
Feb 22, 2021 @ 21:50:05.069 goroutine 134 [IO wait]:
Feb 22, 2021 @ 21:50:05.069 internal/poll.(*pollDesc).wait(0xc000210018, 0x72, 0x0, 0x0, 0xd4457e)
Feb 22, 2021 @ 21:50:05.069 internal/poll.(*FD).Accept(0xc000210000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 22, 2021 @ 21:50:05.069 runtime: program exceeds 10000-thread limit
Feb 22, 2021 @ 21:50:05.069 runtime stack:
Feb 22, 2021 @ 21:50:05.069 runtime.checkmcount()
Feb 22, 2021 @ 21:50:05.069 runtime.mReserveID(0x130fd78)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:1965 +0x79
Feb 22, 2021 @ 21:50:05.069 runtime.handoffp(0xc000073000)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:4826 +0x168
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/proc.go:1137 +0x6e
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/netpoll.go:222 +0x55
Feb 22, 2021 @ 21:50:05.069 internal/poll.(*pollDesc).wait(0xc0001b2418, 0x72, 0x0, 0x0, 0xd4457e)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/net/tcpsock_posix.go:139 +0x32
Feb 22, 2021 @ 21:50:05.069 net.(*TCPListener).Accept(0xc010c4bde0, 0xc0097916e8, 0x18, 0xc000000180, 0x6e9fcc)
Feb 22, 2021 @ 21:50:05.069 net/http.(*Server).Serve(0xc00039c2a0, 0xe46f00, 0xc010c4bde0, 0x0, 0x0)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/net/http/server.go:2937 +0x266
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/net/http/server.go:2866 +0xb7
Feb 22, 2021 @ 21:50:05.069 github.com/urfave/cli/v2.(*App).RunContext(0xc000182c00, 0xe49540, 0xc00003e078, 0xc0000300c0, 0xc, 0xc, 0x0, 0x0)
Feb 22, 2021 @ 21:50:05.069     external/com_github_urfave_cli_v2/app.go:215
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/runtime/netpoll.go:222 +0x55
Feb 22, 2021 @ 21:50:05.069 internal/poll.(*pollDesc).waitRead(...)
Feb 22, 2021 @ 21:50:05.069     GOROOT/src/internal/poll/fd_poll_runtime.go:92```

**Comment by mostynb** [comment]
Interesting...

Can you share the command line args or config file that you're using (excluding any passwords of course)? Do you have a rought idea of how many simultaneous active clients are interacting with bazel-remote, and the maximum number of simultaneous requests they're making?

Also, what kind of specs does the cache server (or container) have? ie how many cpu vcores, how much RAM, and what type of storage?

**Comment by mehmetg** [comment]
I have yet to look into metrics, so I am not sure about the exact numbers at the time of failure, but on a given moment during peak hours we have at least 8 builds running each with 6 concurrent jobs. 

Here are the specs: 
4 cpus 
42 GB of RAM
A portworx volume replicated 3x for storage. It backed by SSD that is not very performant IIRC.

```
"args": [
    "--max_size=350",
    "--tls_enabled=false",
    "--dir=/data",
    "--disable_http_ac_validation",
    "--disable_grpc_ac_deps_check",
    "--enable_endpoint_metrics",
    "--enable_ac_key_instance_mangling"
  ],

```
So what you mentioned about storage not being performant enough sounds familiar.  
As for max threads, the default of 10000 sounds plenty to me.

**Comment by mostynb** [comment]
I will see if I'm able to reproduce the thread-exhaustion by artificially limiting the speed of my test storage. But it might take me a few days to get to it.

In the meantime if you're able to run htop on that machine, it might be worth looking to see if there are a lot of bazel-remote threads in state D (uninterruptible disk sleep) - it's normal to see a few sometimes, but if you see a lot of them at the same time that's not a good sign.

Also maybe there are some settings you can tweak on your storage volume. I'm not familiar with portworx but maybe you can try some of the different performance tuning settings for bazel-remote's volume:
https://docs.portworx.com/install-with-other/operate-and-maintain/performance-and-tuning/tuning/

**Comment by mostynb** [comment]
I haven't been able to reproduce this issue by limiting the disk io speed during testing, unfortunately.

But I did find another thing for you to check: if you run bazel-remote with profiling enabled (set `--profile_port` to a positive integer and `--profile_host` to a reachable IP) and then capture a goroutine stack dump while the system is under load? You can download something like http://localhost:7070/debug/pprof/goroutine?debug=2 (assuming that you set `--profile_port 7070`).

**Comment by mostynb** [comment]
Closing this issue due to lack of feedback. Please reopen this issue if you have more info or if this problem continues.
