### ISSUE TITLE
CANCELLED StatusRuntimeException when setting bazel-remote service as delegate CAS

### ISSUE THREAD

**Issue by zpzjzj** [buchgr/bazel-remote#430]
```
[SEVERE ] [Sun Apr 25 22:06:40 CST 2021] build.buildfarm.worker.PipelineStage run - ReportResultStage::run(): stage terminated due to exception
io.grpc.StatusRuntimeException: CANCELLED: Thread interrupted
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at com.google.bytestream.ByteStreamGrpc$ByteStreamBlockingStub.queryWriteStatus(ByteStreamGrpc.java:283)
        at build.buildfarm.common.grpc.StubWriteOutputStream$1.get(StubWriteOutputStream.java:81)
        at build.buildfarm.common.grpc.StubWriteOutputStream$1.get(StubWriteOutputStream.java:71)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at build.buildfarm.common.grpc.StubWriteOutputStream.getCommittedSize(StubWriteOutputStream.java:303)
        at build.buildfarm.common.grpc.StubWriteOutputStream.isComplete(StubWriteOutputStream.java:313)
        at build.buildfarm.common.grpc.StubWriteOutputStream.write(StubWriteOutputStream.java:242)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:113)
        at build.buildfarm.cas.cfc.CASFileCache.expireEntry(CASFileCache.java:1789)
        at build.buildfarm.cas.cfc.CASFileCache.charge(CASFileCache.java:2475)
        at build.buildfarm.cas.cfc.CASFileCache.putOrReferenceGuarded(CASFileCache.java:2549)
        at build.buildfarm.cas.cfc.CASFileCache.putOrReference(CASFileCache.java:2443)
        at build.buildfarm.cas.cfc.CASFileCache.putImpl(CASFileCache.java:2341)
        at build.buildfarm.cas.cfc.CASFileCache.newOutput(CASFileCache.java:944)
        at build.buildfarm.cas.cfc.CASFileCache$5.getOutput(CASFileCache.java:891)
        at build.buildfarm.worker.shard.Worker$LocalCasWriter.insertStream(Worker.java:161)
        at build.buildfarm.worker.shard.Worker$LocalCasWriter.write(Worker.java:140)
        at build.buildfarm.worker.shard.ShardWorkerContext.insertFile(ShardWorkerContext.java:503)
        at build.buildfarm.worker.shard.ShardWorkerContext.uploadOutputFile(ShardWorkerContext.java:579)
        at build.buildfarm.worker.shard.ShardWorkerContext.uploadOutputs(ShardWorkerContext.java:727)
        at build.buildfarm.worker.ReportResultStage.reportPolled(ReportResultStage.java:97)
        at build.buildfarm.worker.ReportResultStage.tick(ReportResultStage.java:80)
        at build.buildfarm.worker.PipelineStage.iterate(PipelineStage.java:98)
        at build.buildfarm.worker.PipelineStage.runInterruptible(PipelineStage.java:44)
        at build.buildfarm.worker.PipelineStage.run(PipelineStage.java:51)
        at java.lang.Thread.run(Thread.java:756)
        Suppressed: io.grpc.StatusRuntimeException: CANCELLED: Thread interrupted
                at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
                at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
                at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
                at com.google.bytestream.ByteStreamGrpc$ByteStreamBlockingStub.queryWriteStatus(ByteStreamGrpc.java:283)
                at build.buildfarm.common.grpc.StubWriteOutputStream$1.get(StubWriteOutputStream.java:81)
                at build.buildfarm.common.grpc.StubWriteOutputStream$1.get(StubWriteOutputStream.java:71)
                at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
                at build.buildfarm.common.grpc.StubWriteOutputStream.getCommittedSize(StubWriteOutputStream.java:303)
                at build.buildfarm.common.grpc.StubWriteOutputStream.close(StubWriteOutputStream.java:137)
                at build.buildfarm.cas.cfc.CASFileCache.expireEntry(CASFileCache.java:1790)
                ... 17 more
        Caused by: java.lang.InterruptedException
                at io.grpc.stub.ClientCalls$ThreadlessExecutor.throwIfInterrupted(ClientCalls.java:749)
                at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:725)
                at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
                ... 24 more
Caused by: java.lang.InterruptedException
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.throwIfInterrupted(ClientCalls.java:749)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:732)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
        ... 26 more
```

**Comment by mostynb** [comment]
Hi.

I'm not too familiar with buildfarm, but at first glance it seems to be calling QueryWriteStatus, which bazel-remote does not implement. It might be that bazel-remote is not returning "unimplemented" status correctly.

Could you describe your setup in some more detail, and share bazel-remote's logs?

**Comment by zpzjzj** [comment]
My worker config use bazel-remote (v1.3.1) grpc as delegate of fileCAS . 

```
# the worker CAS configuration
cas: {
  # present a filesystem CAS, required to host an exec root
  # the first filesystem CAS in the configuration will be used
  # as the storage for an exec filesystem for an operation
  filesystem: {
    # the local cache location relative to the 'root', or absolute
    path: "cache"

    # limit for contents of files retained
    # from CAS in the cache
    max_size_bytes: 214748364800 # 200 * 1024 * 1024 * 1024

    # limit for content size of files retained
    # from CAS in the cache
    max_entry_size_bytes: 214748364800 # 200 * 1024 * 1024 * 1024

    # whether the file directories bidirectional mapping should be stored in memory (HashMap) or
    # in sqlite
#file_directories_index_in_memory: false
  }

  # whether the transient data on the worker should be loaded into the CAS on worker startup.
  # It can be faster for worker startup to skip loading.
#skip_load: false
}

cas: {
  grpc: {
    instance_name: "extend-cas"
    target: "{remote_cache_service}:9092"
  }
}
```
The error output on bazel-remote service like below :
```
2021/04/26 09:19:47 GRPC BYTESTREAM WRITE FAILED: extend-cas/uploads/3eb04c90-5cfa-4318-b152-7de526daf7e6/blobs/cfabeb6b735df94b32481b51096de4e652cf4e2276dffb8ebc7d7f90a3d1df6f/1621568 rpc error: code = Internal desc = rpc error: code = Canceled desc = context canceled
```

**Comment by mostynb** [comment]
I wonder if you could try building bazel-remote from this branch in my fork? https://github.com/mostynb/bazel-remote/tree/query_write_status_1_3_1

Bazel-buildfarm appears to have some special handling for "unimplemented" and "not found" responses to QueryWriteStatus, so my branch above returns an unimplemented status.

**Comment by mostynb** [comment]
@werkt do you think https://github.com/mostynb/bazel-remote/commit/ecc5dcd588284136c3e1a7a1bc3e3935225e962d would make buildfarm happy?
