### ISSUE TITLE
Panic: invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by prestonvanloon** [buchgr/bazel-remote#451]
```
2021/06/25 13:50:26 bazel-remote built with go1.16.2 from git commit 95beb3c6509eb8980526be47273f15ae531b59a7.
2021/06/25 13:50:26 Initial RLIMIT_NOFILE cur: 1024 max: 524288
2021/06/25 13:50:26 Setting RLIMIT_NOFILE cur: 524288 max: 524288
2021/06/25 13:50:26 Loading existing files in /data. 
2021/06/25 13:50:28 Sorting cache files by atime.
2021/06/25 13:50:28 Building LRU index.
2021/06/25 13:50:29 Finished loading disk cache files.
2021/06/25 13:50:29 Loaded 106322 existing disk cache items.
2021/06/25 13:50:29 Authentication: disabled
2021/06/25 13:50:29 Mangling non-empty instance names with AC keys: disabled
2021/06/25 13:50:29 Starting HTTP server on address :8080
2021/06/25 13:50:29 HTTP AC validation: enabled
2021/06/25 13:50:29 Starting gRPC server on address :9092
2021/06/25 13:50:29 gRPC AC dependency checks: enabled
2021/06/25 13:50:29 experimental gRPC remote asset API: enabled
2021/06/25 13:50:29 Starting HTTP server for profiling on address :6060
2021/06/25 13:50:47 GRPC GETCAPABILITIES

<many GET, READ, HEAD operations>

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9cbdee]

goroutine 1948 [running]:
os.(*File).Name(...)
        GOROOT/src/os/file.go:55
github.com/buchgr/bazel-remote/cache/disk.(*Cache).Put(0xc00042ff10, 0x1, 0xc0000ae333, 0x40, 0x75bd, 0xe67fa0, 0xc0037ac0e0, 0x0, 0x0)
        cache/disk/disk.go:565 +0x46e
github.com/buchgr/bazel-remote/server.(*grpcServer).Write.func2.1(0xc00416e210, 0xc0000ae333, 0x40, 0xc00003a8e0, 0xe6e2b0, 0xc0037ac0e0, 0xc003c2c360)
        server/grpc_bytestream.go:460 +0xb7
created by github.com/buchgr/bazel-remote/server.(*grpcServer).Write.func2
        server/grpc_bytestream.go:459 +0x309
```

**Comment by prestonvanloon** [comment]
Deleting the entire docker volume for `/data` resolved the issue.

**Comment by mostynb** [comment]
Thanks for the bug report.

It looks like bazel-remote failed to create a temp file, and that wasn't checked properly before trying to use it. Potential temp fix to avoid the segfault: https://github.com/buchgr/bazel-remote/pull/452

I'm not yet sure why the tempfile creation might have failed though.

**Comment by mostynb** [comment]
Pushed the segfault fix (this might just turn the segfault into an internal error) and updated the `latest` tag on docker hub. I'll leave this issue open for a while, in case you can collect more info if the problem shows up again.

**Comment by mostynb** [comment]
Closing this, since there have been no reports since the fix. Please re-open if the issue reappears.
